package models

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

// NotificationPrefs is stored as JSONB in the users table.
// @mention always bypasses both type lists.
type NotificationPrefs struct {
	CustomMyTypes  []string `json:"custom_my_types"`  // types for MY assigned orders
	CustomAllTypes []string `json:"custom_all_types"` // types for all other orders + chat
}

var allNotifTypes = []string{
	"status_change", "comment", "mention",
	"attachment", "chat", "product_created", "product_deleted",
}

var myOrdersNotifTypes = []string{
	"status_change", "comment", "mention",
	"attachment", "product_created", "product_deleted",
}

// DefaultNotificationPrefs returns defaults: all notifications on.
func DefaultNotificationPrefs() NotificationPrefs {
	return NotificationPrefs{
		CustomMyTypes:  myOrdersNotifTypes,
		CustomAllTypes: allNotifTypes,
	}
}

// Value implements driver.Valuer for GORM/database serialization.
func (p NotificationPrefs) Value() (driver.Value, error) {
	b, err := json.Marshal(p)
	return string(b), err
}

// Scan implements sql.Scanner for GORM/database deserialization.
func (p *NotificationPrefs) Scan(value interface{}) error {
	var bytes []byte
	switch v := value.(type) {
	case string:
		bytes = []byte(v)
	case []byte:
		bytes = v
	default:
		return fmt.Errorf("NotificationPrefs: unsupported type %T", value)
	}
	return json.Unmarshal(bytes, p)
}

type User struct {
	ID                uint              `json:"id" gorm:"primaryKey"`
	Name              string            `json:"name" gorm:"not null"`
	Email             string            `json:"email" gorm:"uniqueIndex;not null"`
	Password          string            `json:"-" gorm:"not null"`
	RoleID            uint              `json:"role_id" gorm:"not null"`
	Role              Role              `json:"role" gorm:"foreignKey:RoleID"`
	AvatarKey         string            `json:"-" gorm:"column:avatar_key;default:''"`
	NotificationPrefs NotificationPrefs `json:"notification_prefs" gorm:"column:notification_prefs;type:jsonb;not null;default:'{}'"`
	CreatedAt         time.Time         `json:"created_at"`
}

type LoginRequest struct {
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
}

type RegisterRequest struct {
	Name     string `json:"name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
}

type CreateUserRequest struct {
	Name     string `json:"name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
	RoleID   uint   `json:"role_id" binding:"required"`
}

type UpdateUserRoleRequest struct {
	RoleID uint `json:"role_id" binding:"required"`
}

type UserResponse struct {
	ID                uint              `json:"id"`
	Name              string            `json:"name"`
	Email             string            `json:"email"`
	RoleID            uint              `json:"role_id"`
	Role              Role              `json:"role"`
	AvatarURL         string            `json:"avatar_url"` // presigned view URL (generated by handlers, not stored)
	NotificationPrefs NotificationPrefs `json:"notification_prefs"`
	CreatedAt         time.Time         `json:"created_at"`
}

func (u *User) ToResponse() UserResponse {
	return UserResponse{
		ID:                u.ID,
		Name:              u.Name,
		Email:             u.Email,
		RoleID:            u.RoleID,
		Role:              u.Role,
		NotificationPrefs: u.NotificationPrefs,
		CreatedAt:         u.CreatedAt,
	}
}
