package models

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

// NotificationChannelPrefs holds enabled flag and allowed event types for one channel (web or push).
type NotificationChannelPrefs struct {
	Enabled bool     `json:"enabled"`
	Types   []string `json:"types"`
}

// NotificationPrefs is stored as JSONB in the users table.
// Mode: "all" | "my_orders" | "custom"
type NotificationPrefs struct {
	Mode string                    `json:"mode"`
	Web  NotificationChannelPrefs  `json:"web"`
	Push NotificationChannelPrefs  `json:"push"`
}

// DefaultNotificationPrefs returns the default (all notifications on).
func DefaultNotificationPrefs() NotificationPrefs {
	allTypes := []string{
		"status_change", "comment", "mention", "assignment",
		"attachment", "chat", "product_created", "product_deleted", "delivery_reminder",
	}
	return NotificationPrefs{
		Mode: "all",
		Web:  NotificationChannelPrefs{Enabled: true, Types: allTypes},
		Push: NotificationChannelPrefs{Enabled: true, Types: allTypes},
	}
}

// Value implements driver.Valuer for GORM/database serialization.
func (p NotificationPrefs) Value() (driver.Value, error) {
	b, err := json.Marshal(p)
	return string(b), err
}

// Scan implements sql.Scanner for GORM/database deserialization.
func (p *NotificationPrefs) Scan(value interface{}) error {
	var bytes []byte
	switch v := value.(type) {
	case string:
		bytes = []byte(v)
	case []byte:
		bytes = v
	default:
		return fmt.Errorf("NotificationPrefs: unsupported type %T", value)
	}
	return json.Unmarshal(bytes, p)
}

type User struct {
	ID                uint              `json:"id" gorm:"primaryKey"`
	Name              string            `json:"name" gorm:"not null"`
	Email             string            `json:"email" gorm:"uniqueIndex;not null"`
	Password          string            `json:"-" gorm:"not null"`
	RoleID            uint              `json:"role_id" gorm:"not null"`
	Role              Role              `json:"role" gorm:"foreignKey:RoleID"`
	AvatarKey         string            `json:"-" gorm:"column:avatar_key;default:''"`
	NotificationPrefs NotificationPrefs `json:"notification_prefs" gorm:"column:notification_prefs;type:jsonb;not null;default:'{}'"`
	CreatedAt         time.Time         `json:"created_at"`
}

type LoginRequest struct {
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
}

type RegisterRequest struct {
	Name     string `json:"name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
}

type CreateUserRequest struct {
	Name     string `json:"name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=6"`
	RoleID   uint   `json:"role_id" binding:"required"`
}

type UpdateUserRoleRequest struct {
	RoleID uint `json:"role_id" binding:"required"`
}

type UserResponse struct {
	ID                uint              `json:"id"`
	Name              string            `json:"name"`
	Email             string            `json:"email"`
	RoleID            uint              `json:"role_id"`
	Role              Role              `json:"role"`
	AvatarURL         string            `json:"avatar_url"` // presigned view URL (generated by handlers, not stored)
	NotificationPrefs NotificationPrefs `json:"notification_prefs"`
	CreatedAt         time.Time         `json:"created_at"`
}

func (u *User) ToResponse() UserResponse {
	return UserResponse{
		ID:                u.ID,
		Name:              u.Name,
		Email:             u.Email,
		RoleID:            u.RoleID,
		Role:              u.Role,
		NotificationPrefs: u.NotificationPrefs,
		CreatedAt:         u.CreatedAt,
	}
}
